services:
  rgsx:
    build: .
    container_name: rgsx
    # If you prefer prebuilt, replace build with image once published
    # image: ghcr.io/<owner>/<repo>:<tag>
    restart: unless-stopped
    environment:
      - TZ=UTC
      - RGSX_MODE=web
      - WEB_PORT=${WEB_PORT:-8080}
      - RGSX_DISABLE_UPDATER=1
      # Map to your user if needed (or set in Compose with `user:`)
      # - PUID=1000
      # - PGID=1000
    volumes:
      # Point these to your NAS paths
      - ${NAS_ROMS:-./roms}:/roms:Z
      - ${RGSX_SAVES:-./saves}:/saves:Z
    ports:
      - "${WEB_PORT:-8080}:${WEB_PORT:-8080}"   # Web UI/API
    # Optionally enforce user mapping; uncomment and set PUID/PGID
    # user: "${PUID:-1000}:${PGID:-1000}"
